### ISSUE TITLE
wps server hangs on Macos when Reloading Qgis providers

### ISSUE THREAD

**Issue by Nicolasribot** [3liz/py-qgis-wps#27]
py-qgis-wps running on docker on Macos, with variable QGSWPS_SERVER_RESTARTMON set to /tmp/restart_workers.

When touching the file from command line connected to wps docker (touch $QGSWPS_SERVER_RESTARTMON), wps docker is reloading qgis providers as expected but **hangs after that**. Extract of log:

```
wps-wps-1         | 2022-09-26 13:18:12,473     [1]     DEBUG   running update hook for ['/tmp/restart_workers']
wps-wps-1         | 2022-09-26 13:18:12,476     [1]     INFO    Reloading Qgis providers
wps-wps-1         | Application state:
wps-wps-
...
wps-wps-1         | 2022-09-26 13:18:13,344     [52]    INFO    [qgis:52] Qgis application initialized......
``` 
Then I cannot access wps server anymore and must send several ctrl+c to stop container from `docker compose up` command

**Comment by dmarteau** [comment]
Which version are use using ?
Try to reduce your test-case: use one worker, touch restart file without custom providers, ...

**Comment by Nicolasribot** [comment]
docker image: 3liz/qgis-wps:3.26
Ok will test that. I only use the script provider with the default example processing script. I would like in fine to use gdal:rastercalculator processing but did not understand how to declare/enable an existing processing.

**Comment by dmarteau** [comment]
>  I would like in fine to use gdal:rastercalculator processing but did not understand how to declare/enable an existing processing

You may add native providers by adding a provider in `QGSWPS_PROCESSING_EXPOSED_PROVIDERS` (`scripts` and `models` are activated by default because they are user defined algorithms). Note that not all algorithms may be compatible with a
WPS equivalent simply because some parameters may simply not map to their WPS equivalent.  

Afaik algorithms in `gdal` providers do not map: the solution is to wrap a call to the gdal algorithm in your own custom algorithm. (you may have a look at the `tests/unittests/scripts/testcliprasterlayer.py` for an exemple of wrapping a gdal algorithm).

But, at the end, we expect the `processes` api to be enable to map any Qgis parameters.

**Comment by Nicolasribot** [comment]
Thanks for the example. I missed this file. Seems to be what I need.
I'll keep you posted for the QGSWPS_SERVER_RESTARTMON with one worker

**Comment by Nicolasribot** [comment]
Triggering a providers reloading with` QGSWPS_SERVER_RESTARTMON` variable still freezes the application, even with 1 worker. The app scripts folder contains 2 scripts that work (one from example processing script, one adapted from `unittests/scripts/testcliprasterlayer.py`).

I managed to run a `gdal:rastercalculator` based on provided example. I guessed from errors that `type=alg.BAND` is not supported, though I changed to `type=alg.STRING` to pass the band number required for the algorithm and it worked.

Here is the full wps docker log after touching the file:
```
wps-wps-1         | 2022-09-27 10:57:43,447     [1]     DEBUG   running update hook for ['/tmp/restart_workers']
wps-wps-1         | 2022-09-27 10:57:43,457     [1]     INFO    Reloading Qgis providers
wps-wps-1         | Application state:
wps-wps-1         | QGIS_PREFIX_PATH env var:           
wps-wps-1         | Prefix:             /usr/
wps-wps-1         | Plugin Path:                /usr//lib/qgis/plugins
wps-wps-1         | Package Data Path:  /usr//share/qgis
wps-wps-1         | Active Theme Name:  
wps-wps-1         | Active Theme Path:  /usr//share/qgis/resources/themes//icons/
wps-wps-1         | Default Theme Path: :/images/themes/default/
wps-wps-1         | SVG Search Paths:   /usr//share/qgis/svg/
wps-wps-1         |             /home/qgis/.local/share/QGIS/QGIS3/profiles/default/svg/
wps-wps-1         | User DB Path:       /usr//share/qgis/resources/qgis.db
wps-wps-1         | Auth DB Path:       /home/qgis/.local/share/QGIS/QGIS3/profiles/default/qgis-auth.db
wps-wps-1         | 
wps-wps-1         | 2022-09-27 10:57:44,082     [56]    DEBUG   *** Folder settings: Processing/Configuration/SCRIPTS_FOLDERS = /processing/scripts
wps-wps-1         | 2022-09-27 10:57:44,086     [56]    INFO    Processing/Configuration/SCRIPTS_FOLDERS = /processing/scripts
wps-wps-1         | 2022-09-27 10:57:44,086     [56]    DEBUG   *** Folder settings: Processing/Configuration/MODELS_FOLDER = /processing/models
wps-wps-1         | 2022-09-27 10:57:44,088     [56]    INFO    Processing/Configuration/MODELS_FOLDER = /processing/models
wps-wps-1         | 2022-09-27 10:57:44,800     [56]    INFO    Starting Qgis application: 3.26.3-Buenos Aires
wps-wps-1         | 2022-09-27 10:57:44,802     [56]    INFO    Setting offscreen mode
wps-wps-1         | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-'
wps-wps-1         | 2022-09-27 10:57:45,083     [56]    INFO    [qgis:56] Installing cleanup hook
wps-wps-1         | 2022-09-27 10:57:45,084     [56]    INFO    [qgis:56] Qgis application initialized......

```

**Comment by dmarteau** [comment]
I have no clue to  what the problem could be since we cannot reproduce the problem. Would you mind to show  your docker-compose ? 

> I guessed from errors that type=alg.BAND is not supported...

Yes that's the case and, good news, this is fixed in 1.8.1 released a couple of hours ago.

**Comment by dmarteau** [comment]
My two cents is that there is a kind of interprocess dead-lock, but I cannot figure why.

**Comment by Nicolasribot** [comment]
Thanks for the prompt support (and cool for 1.8.1 as we may use band parameters a lot in the future).

I have 2 questions if I may:
 - is it possible to enable WCS for the generated qgs project? (or should I play with file protocol from wps app ?)
 - is there a way in qgis server to browse generated qgs projects, like the catalog allows to do ? As generated projects are stored in their own folders, the qgis server catalog does not see any project and I cannot configure folder names as they are auto-generated.

Here is the docker-compose I use: (I forced a generated folder path for qgis server landing page, just to test if the project worked  (it dit))

```yaml
version: '3.8'
services:
  wps:
    image: 3liz/qgis-wps:3.26
    environment:
      QGSWPS_SERVER_PARALLELPROCESSES:
      QGSWPS_SERVER_LOGSTORAGE: REDIS
      QGSWPS_REDIS_HOST: redis
      QGSWPS_PROCESSING_PROVIDERS_MODULE_PATH: /processing
      QGSWPS_CACHE_ROOTDIR: /projects
      QGSWPS_SERVER_WORKDIR: /srv/data
      QGSWPS_USER: 502:20
      QGSWPS_LOGLEVEL: DEBUG
      QGSWPS_PROCESSING_PROVIDERS: script
      QGSWPS_SERVER_WMS_SERVICE_URL: http://localhost:8380
      # the full path to folder containing qgs project in qgis server. see qgsserver section for value:
      # this is the default dir where qgisserver expect to find qgs projects (in the folder or its subfolders)
      QGSWPS_SERVER_RESULTS_MAP_URI: /etc/qgisserver/
      # from doc: The file to watch for restarting workers. When the modified date of the file is changed,
      # the processing providers are reloaded.
      QGSWPS_SERVER_RESTARTMON: /tmp/restart_workers
    volumes:
      - /Users/b268/Documents/wps/processing:/processing
      - /Users/b268/Documents/wps/projects:/projects
      - /Users/b268/Documents/wps/processing/output:/srv/data
    ports:
      - "127.0.0.1:8080:8080"
  redis:
    image: redis:5-alpine
  qgisserver:
    image: camptocamp/qgis-server
    environment:
      QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES: /etc/qgisserver/b6b5439e-3e52-11ed-ac54-0242ac120003
    volumes:
      - /Users/b268/Documents/wps/processing/output:/etc/qgisserver
    ports:
      - "127.0.0.1:8380:80"
```
